# Generated by Django 4.2.1 on 2023-07-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=32)),
                ('percentage', models.DecimalField(decimal_places=4, max_digits=50)),
                ('expiry_date', models.DateTimeField()),
                ('minimum_purchase_price', models.DecimalField(decimal_places=4, max_digits=50)),
            ],
        ),
    ]
