# Generated by Django 4.2.1 on 2023-07-10 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopping_cart',
            name='product',
            field=models.ManyToManyField(to='inventory.product'),
        ),
    ]
